### ISSUE TITLE
Cannot organize a file: "command 'tsco.organize' not found"

### ISSUE THREAD

**Issue by hoisel** [aljazsim/vs-code-typescript-class-organizer#12] opened 2019-08-01 16:21 UTC

**Comment by aljazsim** [comment] 2020-01-02 02:29
Could not reproduce.

**Comment by zhamid-src** [comment] 2020-01-20 18:20
I am hitting the same issue.  Brand new install.

**Comment by aljazsim** [comment] 2020-01-21 10:34
I cannot reproduce this issue. Could you please provide me with exact steps?

**Comment by zhamid-src** [comment] 2020-02-03 23:25
There are no steps. 

I installed the extension and tried to use it.  That's literally it. If there's a way for me to get logs or something you need then please let me know.

**Comment by krummja** [comment] 2020-05-13 03:25
Same issue here.

**Comment by aljazsim** [comment] 2020-05-13 03:30
If anyone can help me reproduce this issue I'd be very grateful.

**Comment by krummja** [comment] 2020-05-13 03:37
I was able to get this log from the Extension Host:

```
[2020-05-12 23:32:38.642] [exthost] [error] Activating extension aljazsim.tsco failed due to an error:
[2020-05-12 23:32:38.646] [exthost] [error] Error: Cannot find module './src/elements/class-node'
Require stack:
- /home/krummja/.vscode/extensions/aljazsim.tsco-1.0.19/out/extension.js
- /snap/code/32/usr/share/code/resources/app/out/vs/loader.js
- /snap/code/32/usr/share/code/resources/app/out/bootstrap-amd.js
- /snap/code/32/usr/share/code/resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
	at Module._load (internal/modules/cjs/loader.js:622:27)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (/snap/code/32/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:955:769)
	at Function.n._load (/snap/code/32/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:925:106)
	at Function.i._load (/snap/code/32/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:921:391)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at n (/snap/code/32/usr/share/code/resources/app/out/vs/loader.js:15:524)
	at Object.<anonymous> (/home/krummja/.vscode/extensions/aljazsim.tsco-1.0.19/out/extension.js:6:22)
	at Module.o._compile (/snap/code/32/usr/share/code/resources/app/out/vs/loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
	at Module.load (internal/modules/cjs/loader.js:735:32)
	at Module._load (internal/modules/cjs/loader.js:648:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (/snap/code/32/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:955:769)
	at Function.n._load (/snap/code/32/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:925:106)
	at Function.i._load (/snap/code/32/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:921:391)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at require (internal/modules/cjs/helpers.js:68:18)
	at Function.s [as __$__nodeRequire] (/snap/code/32/usr/share/code/resources/app/out/vs/loader.js:33:115)
	at h._loadCommonJSModule (/snap/code/32/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:926:266)
	at h._doActivateExtension (/snap/code/32/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:822:856)
	at h._activateExtension (/snap/code/32/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:821:937)
	at Object.actualActivateExtension (/snap/code/32/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:819:883)
	at e._activateExtension (/snap/code/32/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:598:859)
	at /snap/code/32/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:598:537
	at Array.map (<anonymous>)
	at e._activateExtensions (/snap/code/32/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:598:525)
	at e.activateByEvent (/snap/code/32/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:596:14)
	at h._activateByEvent (/snap/code/32/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:820:618)
	at /snap/code/32/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:829:401
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by gmfc** [comment] 2020-10-26 19:38
Same here

`Command 'TypeScript Class Organizer: Organize Current File' resulted in an error (command 'tsco.organize' not found)`

Working with WSL

**Comment by aljazsim** [comment] 2020-10-27 06:44
Since I can't reproduce this issue and several people can, I would be grateful if someone could produce a PR with the fix for this problem :)

**Comment by Schokokex** [comment] 2020-12-08 16:29
is it an issue with WSL?
im running WSL 2 with Alpine from the Microsoft App Store (maybe check out youtube or a tutorial if you dont know WSL).
Got the same issue, installed the addon and didnt work on any file.
Using the addon via <kbd>Ctrl+Shift+P</kbd>, organize current file

internally, VS Code (with WSL extension) installs extensions in `~/.vscode-server/extensions/`

so basically the question is would it work on linux? :P

**Comment by RaymsDev** [comment] 2020-12-17 13:20
Ubuntu 20.04.1 LTS Here ! Same issue, brand new install and I'm running into the same error.

**Comment by oobleck** [comment] 2021-01-19 20:36
Linux Mint 19.3 and VSCode 1.51.1. I installed this extensions and also get the reported error.

> Since I can't reproduce this issue and several people can, I would be grateful if someone could produce a PR with the fix for this problem :)

@aljazsim We would all appreciate this.

**Comment by azatoth** [comment] 2021-01-29 11:01
I can see the issue; in the uploaded package, in `~/.vscode/extensions/aljazsim.tsco-1.0.20/out/src` there is an `Elements` directory, and not an `elements` directory; i.e. it has been capitalized. renaming this to lowercase and reload vscode makes it work again.

I've no clue how it could have become `Elements` though...

**Comment by azatoth** [comment] 2021-09-21 10:44
@aljazsim I just noticed I had to apply above fix manually again when I had to install this extension again; I would appreciate if it could be fixed in the release.

**Comment by NatoBoram** [comment] 2021-10-31 03:12
This means the error will only happen on case-sensitive filesystems (MacOS & Linux). Well, here's your repro step, @aljazsim ^^

**Comment by azatoth** [comment] 2021-10-31 13:31
> This means the error will only happen on case-sensitive filesystems (MacOS & Linux). Well, here's your repro step, @aljazsim ^^

Problem is that in the repository, the path and any reference to said path is in lowercase. Thus I couldn't figure out a cause for it to become capitalized, except possibly the human factor.

**Comment by iFederx** [comment] 2022-02-04 11:24
> .vscode/extensions

Thanks! In my wsl2 the VSCode folder isn't named `.vscode`, but `.vscode-server`, so the path is
`~/.vscode/extensions/aljazsim.tsco-1.0.20/out/src`

**Comment by aljazsim** [comment] 2022-08-06 08:50
I've just published a new version and checked the installation directory where name casing and seems to be all in lower case as it should be. Please try updating the adding and see if it works.

**Comment by zhamid-src** [comment] 2023-12-26 17:31
I am hitting it again.

I had it working. I uninstalled it and then reinstalled it.  Now I am hitting it again. "elements" is in lower case.

**Comment by aljazsim** [comment] 2023-12-27 07:19
Hmm, the "elements"' directory is in lower case and all the references to it are in lowercase as well. Can you provide me with more information on the issue? Perhaps the output in the output tab at the bottom (Extension Host option)?

**Comment by bartroozendaal** [comment] 2023-12-27 11:08
I have the same issue. Worked until a few days ago. This is the error log from the extension host:
![image](https://github.com/aljazsim/vs-code-typescript-class-organizer/assets/27493817/cd28d754-a53f-4890-b56e-8cc768b2ee1c)

2023-12-27 12:05:48.458 [error] ReferenceError: convertPascalCaseToTitleCase is not defined
    at c:\Users\bartr\.vscode\extensions\aljazsim.tsco-1.0.27\src\configuration\configuration.ts:57:17
    at Array.forEach (<anonymous>)
    at Function.getMemberOrderConfig (c:\Users\bartr\.vscode\extensions\aljazsim.tsco-1.0.27\src\configuration\configuration.ts:53:14)
    at Function.getConfiguration (c:\Users\bartr\.vscode\extensions\aljazsim.tsco-1.0.27\src\configuration\configuration.ts:31:27)
    at Object.<anonymous> (c:\Users\bartr\.vscode\extensions\aljazsim.tsco-1.0.27\extension.ts:67:35)
    at Module.o._compile (c:\Users\bartr\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)

**Comment by aljazsim** [comment] 2023-12-28 07:28
Ok, I've made an update. Please try it out and let me know if this works now!

**Comment by bartrxr** [comment] 2023-12-28 08:31
Yep, seems to be fixed. Thanks a lot. I use your extension daily, so glad it works again.

**Comment by aljazsim** [comment] 2023-12-28 11:05
Awesome, my pleasure! You might consider giving the repo a star, it really means a lot to me ;)

**Closed by aljazsim** 2023-12-28 11:05 UTC

**Comment by ThomasPrioul** [comment] 2025-04-22 20:19
Hi,

I didn't want to dig this up, but I suddenly started hitting this problem on both my machines.
I thought this was related to an update, but seeing this old issue, the problem seems more random ?

One of my machines is running Ubuntu 22.04 and the other one is a WSL with dev containers, so both are linux machines.
Both have the same error "tsco.organize command not found" like reported before.

Looking into the Extension host output window, the error is the following :
```
at require (node:internal/modules/helpers:179:18)
	at Object.<anonymous> (/home/thomas/.vscode/extensions/aljazsim.tsco-2.0.15/out/src/tsco-cli/configuration/configuration.js:6:46)
```

Opening that file on vscode, indeed line 6 points to an unexisting file 'import-source-file-path-quote-type'.
Looking into that folder on my PC, the file exists but with a capital I instead of a lowercase i.
4 files seem affected by this problem.
![Image](https://github.com/user-attachments/assets/a05b0597-36d9-471b-821e-2e90485cc42b)
Renaming the files on my machine with a lowercase "i" fixed the problem.

So there must be a problem with the git index of these files keeping a capital letter or something like that, it is typical when using git on windows as it doesn't care about casing.

It's weird because I was already using WSL/linux on other machines, never had this problem before (perhaps because of using a custom configuration file ?) and thought this broke with a recent update ?

**Comment by andymeadows** [comment] 2025-08-11 15:40
Can confirm this is an issue still (again).  So I hate to necro this but...

```
2025-08-11 11:33:54.236 [error] Activating extension aljazsim.tsco failed due to an error:
2025-08-11 11:33:54.236 [error] Error: Cannot find module '../enums/import-source-file-path-quote-type'
Require stack:
- /home/andy/.vscode-server/extensions/aljazsim.tsco-2.0.15/out/src/tsco-cli/configuration/configuration.js
- /home/andy/.vscode-server/extensions/aljazsim.tsco-2.0.15/out/src/extension.js
- /home/andy/.vscode-server/bin/488a1f239235055e34e673291fb8d8c810886f81/out/vs/workbench/api/node/extensionHostProcess.js

...

```

**Comment by ThomasPrioul** [comment] 2025-08-11 19:48
> Can confirm this is an issue still (again).  So I hate to necro this but...
> 
> ```
> 2025-08-11 11:33:54.236 [error] Activating extension aljazsim.tsco failed due to an error:
> 2025-08-11 11:33:54.236 [error] Error: Cannot find module '../enums/import-source-file-path-quote-type'
> Require stack:
> - /home/andy/.vscode-server/extensions/aljazsim.tsco-2.0.15/out/src/tsco-cli/configuration/configuration.js
> - /home/andy/.vscode-server/extensions/aljazsim.tsco-2.0.15/out/src/extension.js
> - /home/andy/.vscode-server/bin/488a1f239235055e34e673291fb8d8c810886f81/out/vs/workbench/api/node/extensionHostProcess.js
> 
> ...
> 
> ```
> 

Please check my previous comment, you can fix it by renaming the problematic files
